<a href="https://colab.research.google.com/github/alexdcl2003/PAU/blob/main/PRACTICA_1SIMULACION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Objetivo**
- Importar librerias
- definir variables de sus tipos
- realizar operaciones con matrices
- evaluar funciones
- graficar en 2D y 3D

**importar librerias**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import random as rnd

In [ ]:
a=10
type(a)

int

In [ ]:
b=2.0
type(b)

float

In [ ]:
c=False
type(c)

bool

In [ ]:
fruta='naranja'
type(fruta)

str

In [ ]:
len(fruta)

7

### Lista

In [ ]:
D=[4,2,3,5,3,2]
E=[4,2,1,4]
print(D+E)

[4, 2, 3, 5, 3, 2, 4, 2, 1, 4]


In [ ]:
ciudades=['Manta', 'Guayaquil','Cuenca','Loja']
print(ciudades)

['Manta', 'Guayaquil', 'Cuenca', 'Loja']


In [ ]:
ciudades+=['la troncal','Bucay']
ciudades

['Manta', 'Guayaquil', 'Cuenca', 'Loja', 'la troncal', 'Bucay']

In [ ]:
ciudades.append('babahoyo')
ciudades

['Manta', 'Guayaquil', 'Cuenca', 'Loja', 'la troncal', 'Bucay', 'babahoyo']

In [ ]:
#extraer el primer elemento
ciudades.pop(0)
ciudades

['Cuenca', 'Loja', 'la troncal', 'Bucay', 'babahoyo']

In [ ]:
#leer el último elemento de la lista
ciudades[-1]

'babahoyo'

**Libreria Numpy**

In [ ]:
np.pi

3.141592653589793

In [ ]:
np.exp(1)

np.float64(2.718281828459045)

In [ ]:
np.sin(np.pi/4)

np.float64(0.7071067811865475)

In [ ]:
np.sqrt(2)

np.float64(1.4142135623730951)

In [ ]:
2**(1/2)

1.4142135623730951

In [ ]:
t=np.linspace(3,12,101)
t

array([ 3.  ,  3.09,  3.18,  3.27,  3.36,  3.45,  3.54,  3.63,  3.72,
        3.81,  3.9 ,  3.99,  4.08,  4.17,  4.26,  4.35,  4.44,  4.53,
        4.62,  4.71,  4.8 ,  4.89,  4.98,  5.07,  5.16,  5.25,  5.34,
        5.43,  5.52,  5.61,  5.7 ,  5.79,  5.88,  5.97,  6.06,  6.15,
        6.24,  6.33,  6.42,  6.51,  6.6 ,  6.69,  6.78,  6.87,  6.96,
        7.05,  7.14,  7.23,  7.32,  7.41,  7.5 ,  7.59,  7.68,  7.77,
        7.86,  7.95,  8.04,  8.13,  8.22,  8.31,  8.4 ,  8.49,  8.58,
        8.67,  8.76,  8.85,  8.94,  9.03,  9.12,  9.21,  9.3 ,  9.39,
        9.48,  9.57,  9.66,  9.75,  9.84,  9.93, 10.02, 10.11, 10.2 ,
       10.29, 10.38, 10.47, 10.56, 10.65, 10.74, 10.83, 10.92, 11.01,
       11.1 , 11.19, 11.28, 11.37, 11.46, 11.55, 11.64, 11.73, 11.82,
       11.91, 12.  ])

In [ ]:
#indice de masa corporal
peso=np.array([75,76,77,78])
altura=np.array([1.87,1.82,1.83,1.92])
imc=peso/(altura**2)
imc

array([21.44756785, 22.94408888, 22.99262444, 21.15885417])

In [ ]:
#resolver el sistema de ecuaciones
A=np.array([[1,2,3],[2,3,2],[3,1,-1]])
B=np.array([6,14,-2])
X=np.linalg.solve(A,B)
X

array([-5., 10., -3.])

In [ ]:
A=np.array([[1,4,1],[2,-3,2],[3,0,-1]])
B=np.array([[5,3,1],[-1,0,4],[4,2,1]])
print("la suma de la matriz es:")
print(A+B)
print("la resta de la matriz es:")
print(A-B)
print("el producto de la matriz es:")
print(A*B)

la suma de la matriz es:
[[ 6  7  2]
 [ 1 -3  6]
 [ 7  2  0]]
la resta de la matriz es:
[[-4  1  0]
 [ 3 -3 -2]
 [-1 -2 -2]]
el producto de la matriz es:
[[ 5 12  1]
 [-2  0  8]
 [12  0 -1]]


### Numeros aleatorios

In [ ]:
x=round(rnd.random(),3)
x

0.537

In [ ]:
y=rnd.randint(20,100)
y

58

In [ ]:
#Generar 10 numeros aleatorios
M=[round(rnd.random(),2) for e in range(10)]
M

[0.64, 0.13, 0.06, 0.65, 0.46, 0.43, 0.52, 0.11, 0.41, 0.72]

In [ ]:
#Generar una matriz de aleatorios enteros
G=[[rnd.randint(40,100) for e in range(8)]for e in range(10)]

SyntaxError: incomplete input (ipython-input-966649853.py, line 2)